export const ACCOUNT_TYPE_BANK = 'bank'
export const ACCOUNT_TYPE_CASH = 'cash'
export const ACCOUNT_TYPE_DIGITAL_WALLET = 'digital_wallet'
export const ACCOUNT_TYPE_CRYPTO_WALLET = 'crypto_wallet'
export const ACCOUNT_TYPE_BROKER = 'broker'
export const ACCOUNT_TYPE_CREDIT_CARD = 'credit_card'

export const ASSETS_ACCOUNT_TYPES = [
	ACCOUNT_TYPE_BANK,
	ACCOUNT_TYPE_CASH,
	ACCOUNT_TYPE_DIGITAL_WALLET,
	ACCOUNT_TYPE_CRYPTO_WALLET,
	ACCOUNT_TYPE_BROKER,
] as const

export const LIABILITIES_ACCOUNT_TYPES = [ACCOUNT_TYPE_CREDIT_CARD] as const

export const ACCOUNT_TYPES = [
	...ASSETS_ACCOUNT_TYPES,
	...LIABILITIES_ACCOUNT_TYPES,
] as const
